version: '3'

services:
  app:
    build: ./docker/app
    ports:
      - "8001:8001"
    volumes:
      - ./download:/app/download
      - ./log/app:/app/log
    links:
      - chrome
      - mysql

  chrome:
    image: chromedp/headless-shell:latest

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"