// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-05-12 22:21:05.691753 +0800 CST m=+0.086783572

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "title": "kindleM API",
        "contact": {},
        "license": {},
        "version": "0.0.1"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chapters": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "get manga chapter list",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "manga_url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MangaInfo"
                        }
                    }
                }
            }
        },
        "/check/chapter/{chapter_id}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "check chapter all picture download again",
                "parameters": [
                    {
                        "type": "integer",
                        "description": " ",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.PictureList"
                        }
                    }
                }
            }
        },
        "/count/process": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "CountProcess",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ProcessCount"
                        }
                    }
                }
            }
        },
        "/download": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "download chapter list",
                "parameters": [
                    {
                        "description": " ",
                        "name": "download_list",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ChapterRowList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ChapterList"
                        }
                    }
                }
            }
        },
        "/manga": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "download manga list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MangaDetailList"
                        }
                    }
                }
            }
        },
        "/manga/generate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "generate manga",
                "parameters": [
                    {
                        "description": " ",
                        "name": "mobi_info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MobiInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Mobi"
                        }
                    }
                }
            }
        },
        "/search/{query}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "search manga",
                "operationId": "search-manga",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "query",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Manga"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Chapter": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "created": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "index": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                },
                "manga_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "model.ChapterIdList": {
            "type": "array",
            "items": {}
        },
        "model.ChapterList": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "count": {
                        "type": "integer"
                    },
                    "created": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "index": {
                        "type": "integer"
                    },
                    "link": {
                        "type": "string"
                    },
                    "manga_id": {
                        "type": "integer"
                    },
                    "title": {
                        "type": "string"
                    },
                    "total": {
                        "type": "integer"
                    },
                    "updated": {
                        "type": "string"
                    }
                }
            }
        },
        "model.ChapterRow": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                },
                "manga_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.ChapterRowList": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "index": {
                        "type": "integer"
                    },
                    "link": {
                        "type": "string"
                    },
                    "manga_id": {
                        "type": "integer"
                    },
                    "title": {
                        "type": "string"
                    }
                }
            }
        },
        "model.Manga": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "intro": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "integer"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "model.MangaDetail": {
            "type": "object",
            "properties": {
                "ChapterList": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "count": {
                                "type": "integer"
                            },
                            "created": {
                                "type": "string"
                            },
                            "id": {
                                "type": "integer"
                            },
                            "index": {
                                "type": "integer"
                            },
                            "link": {
                                "type": "string"
                            },
                            "manga_id": {
                                "type": "integer"
                            },
                            "title": {
                                "type": "string"
                            },
                            "total": {
                                "type": "integer"
                            },
                            "updated": {
                                "type": "string"
                            }
                        }
                    }
                },
                "alias": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "intro": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "integer"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "model.MangaDetailList": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "ChapterList": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "count": {
                                    "type": "integer"
                                },
                                "created": {
                                    "type": "string"
                                },
                                "id": {
                                    "type": "integer"
                                },
                                "index": {
                                    "type": "integer"
                                },
                                "link": {
                                    "type": "string"
                                },
                                "manga_id": {
                                    "type": "integer"
                                },
                                "title": {
                                    "type": "string"
                                },
                                "total": {
                                    "type": "integer"
                                },
                                "updated": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "alias": {
                        "type": "string"
                    },
                    "author": {
                        "type": "string"
                    },
                    "cover": {
                        "type": "string"
                    },
                    "created": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "intro": {
                        "type": "string"
                    },
                    "link": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "source": {
                        "type": "integer"
                    },
                    "updated": {
                        "type": "string"
                    }
                }
            }
        },
        "model.MangaInfo": {
            "type": "object",
            "properties": {
                "ChapterRowList": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "index": {
                                "type": "integer"
                            },
                            "link": {
                                "type": "string"
                            },
                            "manga_id": {
                                "type": "integer"
                            },
                            "title": {
                                "type": "string"
                            }
                        }
                    }
                },
                "alias": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "intro": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "integer"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "model.Mobi": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "processInfo": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "model.MobiInfo": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "chapter_id_list": {
                    "description": "swag wtf?",
                    "type": "object",
                    "$ref": "#/definitions/model.ChapterIdList"
                },
                "cover": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.Picture": {
            "type": "object",
            "properties": {
                "chapterId": {
                    "type": "integer"
                },
                "created": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "index": {
                    "type": "integer"
                },
                "mangaId": {
                    "type": "integer"
                },
                "referer": {
                    "type": "string"
                },
                "src": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "model.PictureList": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "chapterId": {
                        "type": "integer"
                    },
                    "created": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "index": {
                        "type": "integer"
                    },
                    "mangaId": {
                        "type": "integer"
                    },
                    "referer": {
                        "type": "string"
                    },
                    "src": {
                        "type": "string"
                    },
                    "status": {
                        "type": "boolean"
                    },
                    "updated": {
                        "type": "string"
                    }
                }
            }
        },
        "model.ProcessCount": {
            "type": "object",
            "properties": {
                "chromedp": {
                    "type": "integer"
                },
                "picture": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
